export const tagEntries = [
    { value: 'Acceptans', title: 'Acceptans' },
    { value: 'Aktivitet', title: 'Aktivitet' },
    { value: 'Attrahera', title: 'Attrahera' },
    { value: 'Balans', title: 'Balans' },
    { value: 'Beroende', title: 'Beroende' },
    { value: 'Beskyddande', title: 'Beskyddande' },
    { value: 'Beslut', title: 'Beslut' },
    { value: 'Bryta ner murar', title: 'Bryta ner murar' },
    { value: 'Centrerande', title: 'Centrerande' },
    { value: 'Chakra', title: 'Chakra' },
    { value: 'Depression', title: 'Depression' },
    { value: 'Drömmar', title: 'Drömmar' },
    { value: 'Egenansvar', title: 'Egenansvar' },
    { value: 'Egenvärde', title: 'Egenvärde' },
    { value: 'Emotionellt arbete', title: 'Emotionellt arbete' },
    { value: 'Empati', title: 'Empati' },
    { value: 'Engagemang', title: 'Engagemang' },
    { value: 'Fantasi', title: 'Fantasi' },
    { value: 'Fokus', title: 'Fokus' },
    { value: 'Frid', title: 'Frid' },
    { value: 'Förlåtelse', title: 'Förlåtelse' },
    { value: 'Förståelse', title: 'Förståelse' },
    { value: 'Förverkliga', title: 'Förverkliga' },
    { value: 'Förändring', title: 'Förändring' },
    { value: 'Glädje', title: 'Glädje' },
    { value: 'Gudomlig energi', title: 'Gudomlig energi' },
    { value: 'Guidning', title: 'Guidning' },
    { value: 'Harmoni', title: 'Harmoni' },
    { value: 'Helande', title: 'Helande' },
    { value: 'Hjälplöshet', title: 'Hjälplöshet' },
    { value: 'Hopp', title: 'Hopp' },
    { value: 'Inre glöd', title: 'Inre glöd' },
    { value: 'Insikt', title: 'Insikt' },
    { value: 'Integritet', title: 'Integritet' },
    { value: 'Intuition', title: 'Intuition' },
    { value: 'Jordande', title: 'Jordande' },
    { value: 'Kanalisering', title: 'Kanalisering' },
    { value: 'Karma', title: 'Karma' },
    { value: 'Klarhet', title: 'Klarhet' },
    { value: 'Klärvoajans', title: 'Klärvoajans' },
    { value: 'Kommunikation', title: 'Kommunikation' },
    { value: 'Kontroll', title: 'Kontroll' },
    { value: 'Kraft', title: 'Kraft' },
    { value: 'Kreativitet', title: 'Kreativitet' },
    { value: 'Kvinnliga gudomliga', title: 'Kvinnliga gudomliga' },
    { value: 'Känsla av att vara fast', title: 'Känsla av att vara fast' },
    { value: 'Kärlek', title: 'Kärlek' },
    { value: 'Ledarskap', title: 'Ledarskap' },
    { value: 'Logik', title: 'Logik' },
    { value: 'Lugn', title: 'Lugn' },
    { value: 'Manifestera', title: 'Manifestera' },
    { value: 'Medialiltet', title: 'Medialiltet' },
    { value: 'Meditation', title: 'Meditation' },
    { value: 'Medkänsla', title: 'Medkänsla' },
    { value: 'Medvetenhet', title: 'Medvetenhet' },
    { value: 'Mental funktion', title: 'Mental funktion' },
    { value: 'Minnet', title: 'Minnet' },
    { value: 'Mod', title: 'Mod' },
    { value: 'Moder jord', title: 'Moder jord' },
    { value: 'Natur', title: 'Natur' },
    { value: 'Ny riktning', title: 'Ny riktning' },
    { value: 'Riktning', title: 'Riktning' },
    { value: 'Närande', title: 'Närande' },
    { value: 'Optimism', title: 'Optimism' },
    { value: 'Ordning', title: 'Ordning' },
    { value: 'Personlig utveckling', title: 'Personlig utveckling' },
    { value: 'Positivitet', title: 'Positivitet' },
    { value: 'Problemlösning', title: 'Problemlösning' },
    { value: 'Reinkarnation', title: 'Reinkarnation' },
    { value: 'Renande', title: 'Renande' },
    { value: 'Resande', title: 'Resande' },
    { value: 'Sanning', title: 'Sanning' },
    { value: 'Sexualitet', title: 'Sexualitet' },
    { value: 'Shamanism', title: 'Shamanism' },
    { value: 'Självförtroende', title: 'Självförtroende' },
    { value: 'Släppa taget', title: 'Släppa taget' },
    { value: 'Sorg', title: 'Sorg' },
    { value: 'Spiritualitet', title: 'Spiritualitet' },
    { value: 'Stabilitet', title: 'Stabilitet' },
    { value: 'Stillhet', title: 'Stillhet' },
    { value: 'Studier', title: 'Studier' },
    { value: 'Styrka', title: 'Styrka' },
    { value: 'Säkerhet', title: 'Säkerhet' },
    { value: 'Telepati', title: 'Telepati' },
    { value: 'Tidigare liv', title: 'Tidigare liv' },
    { value: 'Tillit', title: 'Tillit' },
    { value: 'Trygghet', title: 'Trygghet' },
    { value: 'Tålamod', title: 'Tålamod' },
    { value: 'Universellt medvetande', title: 'Universellt medvetande' },
    { value: 'Uppskatta nuet', title: 'Uppskatta nuet' },
    { value: 'Uthållighet', title: 'Uthållighet' },
    { value: 'Vara i nuet', title: 'Vara i nuet' },
    { value: 'Vila', title: 'Vila' },
    { value: 'Visdom', title: 'Visdom' },
    { value: 'Änglakommunikation', title: 'Änglakommunikation' },
    { value: 'Ökad energi', title: 'Ökad energi' },
]